### ISSUE TITLE
wpmudev-dash-notification.php does not exists

### ISSUE THREAD

**Issue by OriginalBildozer** [wpmudev/autoblog#1]
on line 48 of autoblogpremiuim.php well call the file wpmudev-dash-notification.php but it does not exists

**Comment by ivan-ivanic-cm** [comment]
Fixed with https://github.com/wpmudev/autoblog/commit/4b2d97cac4ef9c40bc838cc69146c3968be7358c

If you want to package it for installation on website, you'll have to pull with submodules and then package to zip.
